import GroupsSection from './GroupsSection';
import MediaAssetsSection from './MediaAssetsSection';
import OrganizationTokenField from './OrganizationTokenField';
import { useTranslation } from 'react-i18next';

function OrganizationForm({
  mode = 'create',
  title,
  values,
  error,
  onChange,
  onDiscard,
  onSubmit,
  isSaving = false,
}) {
  const { t } = useTranslation();
  const isViewMode = mode === 'view';
  const isEditMode = mode === 'edit';

  const updateValue = (name, value) => {
    if (isViewMode || !onChange) {
      return;
    }

    onChange({
      ...values,
      [name]: value,
    });
  };

  const updateField = (event) => {
    const { name, value } = event.target;

    updateValue(name, value);
  };

  const handleSubmit = (event) => {
    if (isViewMode || !onSubmit) {
      event.preventDefault();
      return;
    }

    onSubmit(event);
  };

  return (
    <section className="organization-form-page">
      <header className="page-heading">
        <div>
          <h1 className="page-title">{title}</h1>

          <p className="page-subtitle">
            {t('backoffice.orgManagement.editSubtitle')}
          </p>
        </div>

        <div className="form-actions">
          <button
            className="text-button"
            type="button"
            onClick={onDiscard}
            disabled={isSaving}
          >
            {isViewMode
              ? t('backoffice.orgManagement.backToOrgs')
              : t('backoffice.orgManagement.discardChanges')}
          </button>

          {!isViewMode && (
            <button
              className="primary-button"
              type="submit"
              form="organization-form"
              disabled={isSaving}
            >
              {isSaving
                ? t('backoffice.orgManagement.saving')
                : isEditMode
                  ? t('backoffice.orgManagement.saveChanges')
                  : t('backoffice.orgManagement.saveOrganization')}
            </button>
          )}
        </div>
      </header>

      <form
        id="organization-form"
        className="organization-form"
        onSubmit={handleSubmit}
      >
        {error && (
          <p className="form-error" role="alert">
            {error}
          </p>
        )}

        <div className="organization-form-columns">
          <div className="organization-form-main">
            <section className="form-section">
              <h2>
                <span
                  className="material-symbols-outlined"
                  aria-hidden="true">
                  badge
                </span>

                {t('backoffice.orgManagement.coreIdentity.title')}
              </h2>

              <div className="form-grid">
                <div className="form-field">
                  <label htmlFor="organization-id">
                    {t('backoffice.orgManagement.coreIdentity.orgId')}
                  </label>

                  <input
                    id="organization-id"
                    type="text"
                    value={values.id || t('backoffice.orgManagement.autoGenerated')}
                    readOnly/>

                  <small>
                    {t('backoffice.orgManagement.coreIdentity.orgIdHelpText')}
                  </small>
                </div>

                <div className="form-field">
                  <label htmlFor="status">
                    {t('backoffice.orgManagement.coreIdentity.status')}
                  </label>

                  <select
                    id="status"
                    name="status"
                    value={values.status}
                    onChange={updateField}
                    disabled={isViewMode}
                  >
                    <option value="active">
                      {t('backoffice.orgManagement.statusActive')}
                    </option>

                    <option value="inactive">
                      {t('backoffice.orgManagement.statusInactive')}
                    </option>
                  </select>
                </div>

                <div className="form-divider form-field--full">
                  <span>{t('backoffice.orgManagement.coreIdentity.displayNames')}</span>
                </div>

                <div className="form-field">
                  <label htmlFor="name-en">
                    {t('backoffice.orgManagement.coreIdentity.nameEn')}
                  </label>

                  <input
                    id="name-en"
                    name="nameEn"
                    type="text"
                    value={values.nameEn}
                    onChange={updateField}
                    readOnly={isViewMode}
                    required={!isViewMode}
                  />
                </div>

                <div className="form-field">
                  <label htmlFor="name-he">
                    {t('backoffice.orgManagement.coreIdentity.nameHe')}
                  </label>

                  <input
                    id="name-he"
                    name="nameHe"
                    type="text"
                    value={values.nameHe}
                    onChange={updateField}
                    readOnly={isViewMode}
                    required={!isViewMode}
                    dir="rtl"
                    lang="he"
                  />
                </div>

                <div className="form-field">
                  <label htmlFor="student-quota">
                    {t('backoffice.orgManagement.coreIdentity.studentQuota')}
                  </label>

                  <input
                    id="student-quota"
                    name="studentQuota"
                    type="number"
                    min="0"
                    value={values.studentQuota ?? ''}
                    onChange={updateField}
                    readOnly={isViewMode}
                  />
                </div>
              </div>
            </section>

            <section className="form-section">
              <h2>
                <span
                  className="material-symbols-outlined"
                  aria-hidden="true">
                  integration_instructions
                </span>

                {t('backoffice.orgManagement.integrationDetails.title')}
              </h2>

              <div className="form-grid">
                <div className="form-field">
                  <label htmlFor="school-id">
                    {t('backoffice.orgManagement.integrationDetails.ilSchoolId')}
                  </label>

                  <input
                    id="school-id"
                    name="schoolId"
                    type="text"
                    value={values.schoolId}
                    onChange={updateField}
                    readOnly={isViewMode}
                  />
                </div>

                <div className="form-field">
                  <label htmlFor="school-role">
                    {t('backoffice.orgManagement.integrationDetails.israeliSchoolRole')}
                  </label>

                  <input
                    id="school-role"
                    name="schoolRole"
                    type="text"
                    value={values.schoolRole}
                    onChange={updateField}
                    readOnly={isViewMode}
                  />
                </div>

                <OrganizationTokenField
                  schoolId={values.schoolId}
                  value={values.token}
                  onValueChange={(token) =>updateValue('token', token)}
                  readOnly={isViewMode}
                />
              </div>
            </section>
          </div>

          <aside className="organization-form-side">
            <MediaAssetsSection
              logoUrl={values.logoUrl}
              onLogoUrlChange={(logoUrl) =>
                updateValue('logoUrl', logoUrl)
              }
              readOnly={isViewMode}
            />

            <GroupsSection
              groups={values.groups}
              onGroupsChange={(groups) =>
                updateValue('groups', groups)
              }
              readOnly={isViewMode}
            />
          </aside>
        </div>
      </form>
    </section>
  );
}

export default OrganizationForm;
